### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by puritynetwork** [huntabyte/chatty#2]
I want to put it on my own VPS instead of vercel to use it, but when I go there it won't load the page. Can you tell me how to do it?

**Comment by alex6096** [comment]
it's all OK before I type the text in the input area, nothing displays. but when I press enter, the texts can show up correctly,   what's the problem?

**Comment by huntabyte** [comment]
> it's all OK before I type the text in the input area, nothing displays. but when I press enter, the texts can show up correctly, what's the problem?

@alex6096  You'll have to edit the styles in the CSS file.
