### ISSUE TITLE
Catching all errors with messages

### ISSUE THREAD

**Issue by WayneMorganUK** [huntabyte/chatty#8]
Another exceptional sveltekit tutorial. Just one  issue with regard to catching errors. adding the follwing code to `+server.ts` at line 47  catches an error if for example you have an invalid api key
```
if (!moderationRes.ok) {
    const err = await moderationRes.json()
    throw new Error(err.error.message)
}
```

also using `throw new Error(err.error.message)` in line 86 gives a message when you call console.error rather than [ object, object]

**Comment by huntabyte** [comment]
Great points, feel free to open a PR if you'd like :) @WayneMorganUK
